server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false # 关闭驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启sql日志

# 日志格式
logging:
  level:
    org.springframework.security: debug
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'

# 邮件的配置
mail:
  host: smtp.qq.com
  port: 587
  username: 3254168608@qq.com
  password: txmgebfyluiocjgc

# 项目配置
project:
  path: http://localhost:8080/